cv: 5
random_state: 42
n_jobs: 10
model: 'mlp'
scoring: 'balanced_accuracy'
do_feature_selection: False
hyperparameters:
  hidden_layer_sizes: [50, 100]
  activation: ['tanh', 'relu']
  solver: ['adam']
  alpha: [0.1, 0.01, 0.001, 0.0001]
  learning_rate: ['constant','adaptive']

preprocess:
  target_column: 'risk_group'
  normalizer: 'standard' #[standard, l1, l2, minmax, robust, null]
  drop_threshold: 0.8
  categorical_impute: 'most_frequent'
  continuous_impute: 'iterative'
  balancing_method: 'null' #[smote, weighted, null]
  
feature_selection_params:
  step: 2
  min_features: 6
  max_features: 16
  score_threshold: 0.95
