cv: 5
random_state: 42
n_jobs: 10
model: 'randomforest'
scoring: 'balanced_accuracy'
do_feature_selection: False
hyperparameters:
  n_estimators: [25, 50, 100]
  max_features: ['sqrt']
  max_depth: [2, 5, 10, 20]
  min_samples_split: [2, 4, 10]
  min_samples_leaf: [1, 2, 4]

preprocess:
  target_column: 'risk_group'
  normalizer: 'standard' #[standard, l1, l2, minmax, robust, null]
  drop_threshold: 0.8
  categorical_impute: 'most_frequent'
  continuous_impute: 'iterative'
  balancing_method: 'null' #[smote, weighted, null]
  
feature_selection_params:
  step: 2
  min_features: 6
  max_features: 16
  score_threshold: 0.95
