cv: 5
random_state: 42
n_jobs: 10
model: 'xgboost'
scoring: 'balanced_accuracy'
do_feature_selection: False
hyperparameters:
  n_estimators: [25, 50, 100]
  max_depth: [2, 5, 10, 20]
  learning_rate: [0.01, 0.1, 0.2]
  booster: ['gbtree']
  tree_method: ['exact']
  gamma: [0.0, 0.2, 0.4]

preprocess:
  target_column: 'risk_group'
  normalizer: 'standard' #[standard, l1, l2, minmax, robust, null]
  drop_threshold: 0.8
  categorical_impute: 'most_frequent'
  continuous_impute: 'iterative'
  balancing_method: 'null' #[smote, weighted, null]
  
feature_selection_params:
  step: 2
  min_features: 6
  max_features: 16
  score_threshold: 0.95
