cv: 5
random_state: 42
n_jobs: 10
model: 'knn'
scoring: 'balanced_accuracy'
do_feature_selection: False
hyperparameters:
  n_neighbors: [2, 4, 6, 8, 10, 15, 20]
  algorithm: ['ball_tree','kd_tree','brute']
  leaf_size: [1, 5, 10, 20, 30, 40]
  p: [1, 2, 3, 4, 5]

preprocess:
  target_column: 'risk_group'
  normalizer: 'standard' #[standard, l1, l2, minmax, robust, null]
  drop_threshold: 0.8
  categorical_impute: 'most_frequent'
  continuous_impute: 'iterative'
  balancing_method: 'null' #[smote, weighted, null]
  
feature_selection_params:
  step: 2
  min_features: 6
  max_features: 16
  score_threshold: 0.95
