cv: 5
random_state: 42
n_jobs: 10
model: 'svc'
scoring: 'balanced_accuracy'
do_feature_selection: False
hyperparameters:
  kernel: ['linear', 'rbf', 'poly']
  gamma: [0.1, 1, 10, 100]
  C: [0.001, 0.01, 0.1, 1, 10, 100]
  degree: [1, 2, 3, 4]

preprocess:
  target_column: 'risk_group'
  normalizer: 'standard' #[standard, l1, l2, minmax, robust, null]
  drop_threshold: 0.8
  categorical_impute: 'most_frequent'
  continuous_impute: 'iterative'
  balancing_method: 'null' #[smote, weighted, null]
  
feature_selection_params:
  step: 2
  min_features: 6
  max_features: 16
  score_threshold: 0.95
